export const GET_CHARACTER_LIST = 'GET_CHARACTER_LIST';
export const GET_CHARACTER_ITEM = 'GET_CHARACTER_ITEM';
export const CLEAR_CHARACTER_ITEM = 'CLEAR_CHARACTER_ITEM';
export const WRITE_PARAMS = 'WRITE_PARAMS'
export const CLEAR_FILTER = 'CLEAR_FILTER,'
export const MODAL_STATUS = 'MODAL_STATUS';
